### ISSUE TITLE
Add vikipedi.pw mirror 

### ISSUE THREAD

**Issue by rbcet** [halileohalilei/ZeroWiki#1]
Hocam 0wikipedia yerine vikipedi.pw yapılabilirse daha güzel olabilir.

**Comment by halileohalilei** [comment]
Looks like vikipedi.pw is no longer functional.

**Comment by rbcet** [comment]
https://en.vikipedi.pw/wiki/Yield_(engineering)

It is not functional on its own.

**Comment by halileohalilei** [comment]
Yes, so it seems. My bad, reopening the issue.
