### ISSUE TITLE
Add setting to use Wikipedia design by default

### ISSUE THREAD

**Issue by metagn** [halileohalilei/ZeroWiki#2]

**Comment by halileohalilei** [comment]
Can you elaborate on this issue please?

**Comment by metagn** [comment]
See this? ![image](https://user-images.githubusercontent.com/10591326/33514449-4b662ada-d765-11e7-9350-1e1ea73daaf7.png)

By default ZeroWiki links to the normal wikizero.com/lang/page, I think there should be a setting that links to wikizero.com/wiki/lang/page which has the regular wikipedia design.
