### ISSUE TITLE
Chrome'da "Bu siteye ulaşılamıyor" hatası

### ISSUE THREAD

**Issue by ghost** [halileohalilei/ZeroWiki#22]
Chrome'da Wikipedia sayfasına girmeden önce anlık olarak "Bu siteye ulaşılamıyor" hatası alıyorum.Yani hata anında görünüp kayboluyor.

Bu hata Firefox Quantum'da yok ve Firefox'ta doğrudan Wikipedia'ya girebiliyorum.Nedense Chrome'da bu hatayı görüyorum.Neden kaynaklanıyor olabilir?İsterseniz video da çekebilirim.

`0wikipedia.org` yansımasını kullanıyorum.

![adsiz](https://user-images.githubusercontent.com/34379403/53995510-486b0480-4146-11e9-9432-944235741cd0.png)

**Comment by halileohalilei** [comment]
Yakın zamanda çıktığım bir güncellemeden sonra bu bende de ara ara olmaya başladı. Seçtiğiniz yansımaya yönlendirmeden önce gerçek Wikipedia sayfasına girmeye çalışıyor sanırım, o yüzden böyle bir hata görünüyor olabilir. Her seferinde olmadığı için çok üzerinde durmamıştım ancak rahatsız ediyorsa sebebine bir bakabilirim. 

Diğer yansımalarda da aynısı oluyor mu, yoksa yalnızca 0wikipedia.org seçiliyken mi oluyor?

**Comment by ghost** [comment]
Diğer yansımalarda da aynı sorun var.Yalnız bende her seferinde bu uyarı karşıma çıkıyor.Acelesi yok ancak sebebine bakarsanız iyi olur bence.
Teşekkürler.
